### ISSUE TITLE
Style the whole `crmPack` package, so that `styler` does not change the files anymore.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#493]
If R code style is not up-to-date, styling will automatically be applied and restyled files will be automatically committed o the branch, this is due to this configuration. This is due to `auto-update: true` configuration in `./.github/workflows/check.yaml` file:
```
  style:
    if: github.event_name == 'pull_request'
    name: Style Check 👗
    uses: insightsengineering/r.pkg.template/.github/workflows/style.yaml@main
    with:
      auto-update: true
```
This causes that in case of some changes (that do not not exceed a few lines), to some large file (e.g. >2000 lines of the code) that has not been yet cleaned up, the whole file is then possible changed by the styler. Since we do not want to disable `styler` in automation check, we want to clean the whole package automatically by the styler within this issue.
